### ISSUE TITLE
%* for filename missing from the command batch file.

### ISSUE THREAD

**Issue by rnwolf** [novoid/integratethis#1]
On Windows 10, when I run the integratethis command  like this:

```
integratethis date2name
```
I get this, which works fine.

```
@ECHO OFF
REM change drive, e.g., D:
%~d1
REM change directory, e.g., D:\data processing\subdir\
cd %~dp1


C:\Users\rnwol\workspace\integratethis\venv\Scripts\date2name.exe %*

REM set /p DUMMY=Hit ENTER to continue...
```

But when I run any of the other integratethis commands that require further command line options the %* is missing from the resulting batch file.

```
integratethis appendfilename --parameter="--verbose" --confirm
```
results in, which is missing %*, for the file names.

```
@ECHO OFF
REM change drive, e.g., D:
%~d1
REM change directory, e.g., D:\data processing\subdir\
cd %~dp1


C:\Users\rnwol\workspace\integratethis\venv\Scripts\appendfilename.exe --verbose

set /p DUMMY=Hit ENTER to continue...


```

PS: The line on the repo homepage 

```integratethis time2name``` 

should most probably be 

```
integratethis date2name  --parameter="--withtime" --displayname "time2name"
```

**Comment by novoid** [comment]
Hi @rnwolf,

> PS: The line on the repo homepage
> 
> `integratethis time2name`
> 
> should most probably be [...]

No, this is correct. I hard-coded this so that time2name is actually internally mapped to the command you suggested. I admit that this is not obvious but it might be helpful because many people would like to have `time2name`.

**Comment by novoid** [comment]
Hi @rnwolf (again),

and congratulations to be the first one to open an issue for this project! Very much appreciated!

> But when I run any of the other integratethis commands that require further command line options the %* is missing from the resulting batch file.
> 
> ```
> integratethis appendfilename --parameter="--verbose" --confirm
> ```

Unfortunately, I don't have access to a Windows machine at the moment. However, from looking at the code, I assume that I thought using `--parameter` gives total control to the user. Therefore, the user has to use something like  

```
integratethis appendfilename --parameter="--verbose %*" --confirm
```

If this holds true, I absolute agree that the README is misleading here.

So: can you confirm that adding the `%*` to the parameter is solving the issue and this works without further escaping?
If so I suggest I will adapt the README as well as the help screen so that it is absolutely clearly communicated that the wildcard parameter needs to be added by the user since this is overwriting _all_ parameters.
This does make sense when you think of commands that do not require the `%*` at all. And for them, `integratethis` should work as well.

**Comment by novoid** [comment]
After further studying the source code, I came to the conclusion that my assumption above is true: the `--parameter` overwrites the complete pre-defined parameter sets including the file matching pattern `%*`. I made sure that the `-h` as well as the README make sure that this can not be misunderstood not. I also added the `time2name` example as a note.

If you do have any further issue with that, please do reach out to me again. 

Thanks for reporting this issue and have a nice day!
