### ISSUE TITLE
Manual installation of Integrate this showing errors

### ISSUE THREAD

**Issue by AlpsDevABE** [novoid/integratethis#2]
Hey Novoid,

Unfortunately due to my work environment I am unable to use Pip install to directly install your applications in the standard way. When I did this on my personal computer I thought that as I was doing a git checkout of the repo and doing pip install within the parent directory of the folder name that I was actually installing it from the .git. Turns out I was not. I don't know how to install your scripts directly from the .git repo. If you can add that to the guide, that would be nice.

So what I have done is downloaded the .whl directly from the pip website https://pypi.org and one by one installed the dependencies and scripts.

I'm running python 3.7.3 (32-bit) on windows
My pip list looks like this
```
Package        Version
-------------- ------------
appendfilename 2019.10.29.1
args           0.1.0
clint          0.5.1
colorama       0.4.3
date2name      2018.5.9.1
filetags       2019.12.22.1
integratethis  2020.1.8.1
move2archive   2018.2.3.2
pip            19.0.3
pyreadline     2.1
pywin32        227
setuptools     40.8.0
```

I was able to integratethis date2name, but not time2name:
```
integratethis time2name

Traceback (most recent call last):
  File "c:\users\name\appdata\local\programs\python\python37-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\name\appdata\local\programs\python\python37-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\name\AppData\Local\Programs\Python\Python37-32\Scripts\integratethis.exe\__main__.py", line 9, in <module>
  File "c:\users\name\appdata\local\programs\python\python37-32\lib\site-packages\integratethis\__init__.py", line 387, in main
    assert(os.path.isfile(command_in_path))
```

Any thoughts?

**Comment by novoid** [comment]
Hi @AlpsDevABE,

I understand your situation and your rationale.

However, I would have tackled the issue in a different way. Instead of trying to run `integratethis` or using `pip` with local files, I would have used the manual installation instructions I have added for my tools (without `integratethis`).

To be honest, I don't have the knowledge of helping you here with this approach.

Manually setting up `time2name` for File Explorer would look similar to:

```
Windows Registry Editor Version 5.00

;; for files:

[HKEY_CLASSES_ROOT\*\shell\date2name]
@="time2name (single file)"

[HKEY_CLASSES_ROOT\*\shell\date2name\command]
@="C:\\Python36\\python.exe C:\\Users\\USERNAME\\src\\date2name\\date2name.py --withtime -i \"%1\""
```

Assuming that this will solve your issue with `time2name`, I'll close this issue here.

If you still got an issue with the manual setup of `date2name` this way, please open an issue in the `date2name` project so that others profit from the solution.

If anybody with deeper knowledge of `pip` and local install from files, please add comments.
